services:
  - type: web
    name: kfc-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        sync: false

